### PR TITLE
Adjust breakpoints to match our custom CSS

### PR DESCRIPTION
**Pull request by sfrdmn**
Just went ahead and forked Tachyons for any potential further changes we need

### CODE REVIEW

**Comment by sfrdmn** [comment]
Although, hmm, I was hoping JSConf used the same breakpoints to make this easier, but I see now they don't :/ Maybe we don't need to bother with the fork?

**Review by Kriesse — CHANGES_REQUESTED** [review]
Looks good, but we need a separate fork for cssconf (see other comment in the tachyons PR)

**Comment by sfrdmn** [comment]
@Kriesse Right, of course, not sure what I was thinking XD I can't fork on JSConf, I don't think, though

**Comment by sfrdmn** [comment]
Closing. Upped separate branch `cssconf-2018` which is intended to be used as the release branch

**Pull request closed without merging**
